### ISSUE TITLE
Native Look and Feel

### ISSUE THREAD

**Issue by manuels** [Icy-imaging/Icy-Kernel#645]
While I have the impression that Icy is quite a useful software, I strongly dislike the look and feel.
Looks like it uses the substance library on top of swing.
Is it possible to somehow change the UI look and feel back to the native one? (In my case Linux/GTK)

**Comment by Stephane-D** [comment]
Indeed Icy uses Substance LAF, we chosen that solution because we wanted to have a similar look whatever is the OS giving a unique appearance to the software.
I admit it would not please everyone but unfortunately there is no way to use the native LAF as Icy does have some internals dependencies on substance LAF.
Still we hear your complain about having a fixed LAF and that will inspire us in our choice on future development :)

**Comment by manuels** [comment]
Ok, thanks for the quick feedback!

**Comment by Stephane-D** [comment]
You're welcome !
