### ISSUE TITLE
File in .lif format not opened properly

### ISSUE THREAD

**Issue by giocard** [Icy-imaging/Icy-Kernel#650]
File generated from LAS X Widefield and obtained from experiment with multiple locations, time series of stacks (3 channels). File linked ( https://datashare.biochem.mpg.de/s/QJe4YU5LM4BsmAb ) is drastically reduced, but reproduces the issue: can open correctly on LASX or Fiji, but not on ICY, where the order of the images seems random. 
Thanks,
Giovanni

**Comment by Stephane-D** [comment]
Hi Giovanni,

Indeed this is because we are using an older version of Bio-Formats (the library which open the LIF image) which has a bug in the ordering. The problem is that the current last version of Bio-Formats bring troubles with Micro-Manager in Icy so we need to find a workaround so we could use the last version of Bio-Format withtout troubles.
If you don't need Micro-Manager then you can simply download the last version of Bio-Formats from here :
https://downloads.openmicroscopy.org/bio-formats/5.9.0/artifacts/bioformats_package.jar
Then replace the lib/bioformats.jar file in the Icy folder by the one you just downloaded (change the name  to match name in icy).

**Comment by giocard** [comment]
Hi Stephane,

thank you for the explanation. I followed your suggestion and now everything works fine.
Thanks again!
Giovanni
