### ISSUE TITLE
Abbreviated menu texts, tooltips etc

### ISSUE THREAD

**Issue by robna** [Icy-imaging/Icy-Kernel#653]
I am seeing nearly all menu texts and tooltips incomplete and cut off by ... with no option to reveal the full content.
Version: 1.9.10.0
System: Manjaro Linux
Tooltip example:
![screenshot from 2019-01-10 15-16-58](https://user-images.githubusercontent.com/26489593/50974281-2c9f0580-14eb-11e9-83b0-12a53b755421.png)

**Comment by Stephane-D** [comment]
Look like the font magnification isn't correctly handled by your JVM.
Which version of java are you using ?
We strongly recommend to use java 8 (last if possible) from Oracle (avoid OpenJDK as GUI parts often suffers from bugs).
Also you can try to change the GUI text size from Icy preferences but i think that is not the problem here.

**Comment by robna** [comment]
Ok, that seems to have been the problem. I was on jvm open-jdk 10. I
also tried open-jdk 11 wich results in the same display problems.

I installed then oracle jre 8 and the texts are visible now.

Thank you!

**Comment by Stephane-D** [comment]
Glad you were able to fix it :)
