### ISSUE TITLE
Problems opening compressed Nifti files

### ISSUE THREAD

**Issue by Dahaniel** [Icy-imaging/Icy-Kernel#654]
Opening a nii.gz file in icy is super slow as compared to opening a nii file of the same size. Actually opening a 1.5 GB nii.gz file is not possible as it takes forever, when unzipped the resulting 1.7 GB nii file loads in a few seconds.

**Comment by Stephane-D** [comment]
Thanks for your report :)
Icy is using Bio-Formats library internally to open nii image files.
Bio-Formats always focus on accuracy before performance, so that may explain the problem. Still given your input (infinite time for zipped file), it may be a bug here.
Here's the Bio-Formats bug report page : 
https://docs.openmicroscopy.org/bio-formats/6.0.1/about/bug-reporting.html
